apiVersion: v1
kind: Pod
metadata:
  name: scrubs-api
spec:
  containers:
    - name: scrubs-api
      image: martinsimango/scrubs-api:v0.1.0
      ports:
        - containerPort: 80
          name: http

