apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system-prod
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./k8s/prod
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system-dev
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./k8s/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system