---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: docker-credentials
  namespace: dev
spec:
  encryptedData:
    .dockerconfigjson: AgAKVawez8QCcVWuwjUDMQjVwgHj+9aM21/+//wnpZ8WlJwO7PKZBp1MxAw2VAO/0JxP8jjl2sMEszZX8zkyCs6BYvTjO0fInbZwf3sNJGqN2F8eejaDsL1mW3df36fSsIFF8nT1jC0XW82Ze0EkjyxSrcQbSqMihNNwpnpy6jxJWr9JjuvyEI2jFa5L6HPJ9xU0X3bv6GNPAU3xQbAVWq5HomJTszNnxtTkyd8tS8Glj1dL9Xat6UecZ8UyTi+ZSimhR/1ul+GDagHFHBFcG4KTyMARtwFnYmg15lbANEIk2NCBTzstLyNkF0FGU8JuAGJCF2d36MTrLGpm8a5/xWTwC4U5s1m/gt0lwqSElkhx6Kzo5fn8kGhr4l4LwxcfoYQxwbAsN/67TeCHxulisgdh4nY+lnukhvL/UxO8E1JRgQOXc5PI4TOjbDlsxIDsn+o79wD+hNjqaPfbo/qFpBj6mSXxHM/VRJi/YnJpo4N5ZeKZI1vQLQK4MlLMsZ3rrAqive8fetUbKb8zX8gMBH0WyA2G4weCaiKtLIEhiejIvRNYoQnsPEbzbQeQcmLKyD4mCYfTu4Kveb8T+5mCl9IdvGQsZvJTpZholIiaX0ZPuQjCvp6FSqBhmZEtDkLGhk3DI+Qeiu+Mx4dmimspcCRd73EdWqfJRTuewHuQwFPey+T8SW9awsZErjLygWMuP1aqN7+sCOQkvIPq+64kG5H5oN77ZgiWKViMnN40GCLcnGkClZD0ZlHh/8hY/ycfadRUOXvjRp+lrtJ5pqfDWZ7tsPWeLz+lEfTrR3NuHc9nb5GoOpAxorwaYL0SzgKOyTv35+q1VtDQH3XWmqM0Ow3mlvCXgWwTFDQ3TB+Btbn/Rj2ayC4Q1FSdE8iGhDMNxg==
  template:
    metadata:
      creationTimestamp: null
      name: docker-credentials
      namespace: dev
    type: kubernetes.io/dockerconfigjson
