---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgACRa135eUv16jqYTE/2VhBFO40ZSlMxswvxB4RcLG5Jje2WhAYAz76sAY6xGtPw1sh8V0NJTn3Kh+hwQAg+hb/WDtczH9VNO7XprgJlLMxPS4DET/eFuPSIAO9pWc4WRWyM8LWivqqjMucfULBLt4zLraQCqCBMm5SwFYWuYosuZaXgiHOuvktcfZ8R++8bnmLqkqeGjYDFgYceDVhq6YvcBpoF6PT4DcKHrkjeYU5Hit9Cv8R7lEkudrHWw+0CT9ODGXMLaNOBuoApUafB5TFMlYE3j6ijSO+W9jhLWf5Zv558XGA2C5CtaPOPLMo2P0lIib5x04yz7PyofP/yuERP4QEB0sf0cVSd/07PZZQPPt4z5/VvFxxDcqIhkCNUeb5V9tYflDlOF/8nSKHPNTlzcmZD4m6yrntJaQxgvSJWIJMllJWT3MNUvr0pFyZkjQzqBbGCWyUymj8i7oG2GYnkQPKjTg4TcEyR9qgpF9euGDFen9SXBTc4hbPgi1FuzKGwwKlmmZbFRkUOPZ5HTXtPZwfWkeHjObhGwx1+EbPqcIBgNoqbjaicz7u1N+BqwGhA/A8LcstFkOIopL0EwxG4mzqoq+bmkgxFYvLN5mIe32ZobTC2s9M8R+GBMkHaDS8VM0AHkcMLfvreB0APvdpwMn/UxI+lAyd27ojcW6M7ieCd/HHeuwnTN9om2yYfdkUT6oeEo3Y9qdLDJeiWFl1zwo=
    admin-user: AgApckx3bX2+wbrRl0Z3CzSeZU2t8FyBUQmzrAz9dMwtAGymSlcIc5BeyXmiRHSfCr6e6wp5GQcsVJq2q7d8HN0ahV7xezMT1ahuDgBWiEEgQAe6ToQfoFRXTVAXvKn/ks+NHSZHxr0XrN92qdtjAsaHNCvd2iFvYHl26DRJa2IJ47fc0IJ+9H5YbeygSFgSWpSOX1Lg4yFQH6cERWM0lj2RzdwqYPLf2/VTMroQXVjVWrQUEXcSA+9XH6c/JPaIOnvWWGnQufUeHQmXHS/YM65y3s/ezbzeLsw7BFKtTg+HLnPF3huI4OBGVCttsX7EV6M4Dz98974kBZzf/AoLlKPp6KjcEx0F7SdsL+cagZOjKQkOFhoES7gz056Sf38PAkVFZ8sKRLMwoGqf6zg2mPusK3kOF35f2rYYpcd34prUBYYvJKCDMLmmzqKjJo85wyakHyPTPoznuOhEU6hC5zKOZygV0C5RaORIgHIVxzdM0Brbp3dC8Gz2gYDY7/M/XA5YDSitir/VW8cHJbbdMLV8THxOfkN8WAyYTuI/aZ6Csgj0J8CjIFP5V7tow6Twk46wQlbo2Db90bIAGR++HOKPUjFW0A6GBDsC/FFeS/UdjmJVwJgrtBdfYC0Qe0TZ3Le/VlipwlXOPlE0KbjJwFBRFhbJda4PcWCZj5fa1nN4ga/yFgrtSwQLZMkHcnYedjF5Sil47A==
  template:
    metadata:
      creationTimestamp: null
      name: grafana
      namespace: monitoring
