---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: docker-credentials
  namespace: prod
spec:
  encryptedData:
    .dockerconfigjson: AgAXa0sPGzzpGyf4OMnHQtKZDVvsVw4IV2lnFnONLtC7t38a7FerFmE5TsNx9nCB4c8JTyOEo6IGFKL00zr6zFpUQ7bZUOtsbYGFud7UyKHhu1GbH9iA0CnluGq3cfDPyHKrjL1RrUR9kVvyLijUjE7dxvpLDKvD6xo9UVJQDTvvgS3UBylq5Az3K2eDh8REB3Ii7Wi2mIf+qHkvEfNBYEXxPWSFLis/hK5MnALCX1p6f0HA62LK9YEKUI8EQE5rRVLjd/ZOrb3iFJjRE8s/m45YT+DK8qB4NEKgk8UFzYEJk5ge/POht5U63OhhQvkkjdvDroObAzqvxwtyvNV1Bagd3q1Ffhb4iD9d1uJU8ac47qC7Z2SSS7v1f/1zxWf2VRQ+G5XFr+QWaW6eapgyQtM4V7xkSgYG7h3pRFJU7HI69GaF9yWa40H+BCGKsPy4ORJ9ag15uVihUtl1rKz4Nuh8WbKaWqNUWvrvNCFpE0pn9zxpDMscs74cdvKOmc1WJVWFpNORAyVxnU7zHGz90x7Dx2YMW5jdPpicZ8DYjOXJAewcU/AQNjYEnD+skOSkV7dfz++6ycDRIT12XzOgFcG+Y8XfFWmWq9XJe5zAvDrDLDr2pdaku/evdKZRac3o5FXYlGVflRMeA9Z/XPf8Cgruy2CvkGkqVumXIQ9FUdc0JHOl/xiPwX51lbo6ADwtCl5AJfiUh4d2X+Gds0ZX7HezNjMcdJJdqg6fiIhE7lI0B22UYCe7yCreTINlitgvaFZJ53e0h5YbdbKCkDWQTMkK1UcmBDt3ZD/AIHgraqrP1hUDZx3WO4aWTcrHdQ42h9j+U+qDNZLkYRBpOYaddBDGIZxHPfkSP105gDaREn0nSuirofWfsmpMrMaRWjitsg==
  template:
    metadata:
      creationTimestamp: null
      name: docker-credentials
      namespace: prod
    type: kubernetes.io/dockerconfigjson
