apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  interval: 10m
  path: "./k8s/sealed-secrets"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  dependsOn:
    - name: flux-system

---
apiVersion: kustomize.toolkit.fluxcd.io/v1 
kind: Kustomization
metadata:
  name: prod
  namespace: flux-system
spec:
  interval: 5m 
  path: "./k8s/overlays/prod"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  dependsOn:
    - name: sealed-secrets



