apiVersion: kustomize.toolkit.fluxcd.io/v1 
kind: Kustomization
metadata:
  name: prod
  namespace: flux-system
spec:
  interval: 30s # Set the interval to 30 seconds
  path: "./k8s/overlays/prod"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  interval: 10m 
  path: "./k8s/clusters/prod/sealed-secrets"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
