apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-dns-record
  namespace: jobs
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: dns-updater
              image: martinsimango/update-dns:latest
              command: ["./update-dns.sh","shukomango.co.in."]
              envFrom:
                - secretRef:
                    name: aws-creds 
          

