apiVersion: v1
kind: ConfigMap
metadata:
  name: oidc-iam-pod-role
data:
  AWS_DEFAULT_REGION: eu-west-1
  AWS_ROLE_ARN: arn:aws:iam::648421211512:role/route53-dns-updater
  AWS_WEB_IDENTITY_TOKEN_FILE: /var/run/secrets/oidc-iam/serviceaccount/token

--- 
apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-dns-record
  namespace: jobs
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: updater
              image: amazon/aws-cli:latest
              command: ["update-dns.sh","shukomango.co.in."]
              volumeMounts:
                - mountPath: /var/run/secrets/oidc-iam/serviceaccount/
                  name: aws-token
              envFrom:
                - configMapRef:
                    name: oidc-iam-pod-role
          volumes:
            - name: aws-token
              projected:
                sources:
                - serviceAccountToken:
                    path: token
                    expirationSeconds: 600
                    audience: sts.amazonaws.com



