[package]
name = "scrubs"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = {version = "0.7.9"}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.68"
tokio = { version = "1.0", features = ["full"] }
